name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout this repo
        uses: actions/checkout@v2
        with:
          path: midside

      - name: checkout libdaisy
        uses: actions/checkout@v2
        with:
          repository: electro-smith/libDaisy
          path: libdaisy
          
      - name: checkout daisysp
        uses: actions/checkout@v2
        with:
          repository: electro-smith/DaisySP
          path: daisysp

      - name: make
        run: |
          cd midside
          make
