name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout this repo
        uses: actions/checkout@v2
        with:
          path: midside

      - name: checkout libdaisy
        uses: actions/checkout@v2
        with:
          repository: h2g2guy/libDaisy
          path: libdaisy
          
      - name: checkout daisysp
        uses: actions/checkout@v2
        with:
          repository: h2g2guy/DaisySP
          path: daisysp
          
      - name: install tooling
        run: sudo apt-get install gcc-arm-none-eabi
      
      - name: build libraries
        run: |
          cd libdaisy
          make
          cd $GITHUB_WORKSPACE
          cd daisysp
          make

      - name: make
        run: |
          cd $GITHUB_WORKSPACE
          cd midside
          make
